# Generated by Django 4.0.3 on 2022-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_localuser_city_alter_localuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
