# Generated by Django 4.0.3 on 2022-03-15 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(default='-', max_length=255)),
                ('ipAddress', models.GenericIPAddressField(default='127.0.0.1')),
                ('browser', models.CharField(default='localhost:chrome', max_length=255)),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_shop', to='users.localuser')),
            ],
        ),
    ]
