# Generated by Django 4.0.2 on 2022-02-19 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherauth',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=32, null=True)),
                ('lastName', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('dob', models.DateField(null=True)),
                ('registrationDate', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 16, 33, 53, 482420))),
                ('address', models.CharField(max_length=64, null=True)),
                ('pincode', models.IntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publisherauth')),
            ],
        ),
    ]
