# Generated by Django 4.0.2 on 2022-02-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_alter_publisher_registrationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('publisherShopId', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=64)),
                ('publisherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher')),
            ],
        ),
    ]
