# Generated by Django 4.0.2 on 2022-02-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='contact',
            new_name='contactId',
        ),
        migrations.RenameField(
            model_name='publisherauth',
            old_name='contact',
            new_name='contactId',
        ),
    ]
