# Generated by Django 4.0.2 on 2022-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_rename_contact_publisher_contactid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopPincode',
            field=models.CharField(default='208012', max_length=6),
        ),
    ]
