# Generated by Django 4.0.2 on 2022-02-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_shop_shoppincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='publisherShopId',
            new_name='shopId',
        ),
    ]
