# Generated by Django 4.0.2 on 2022-02-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_rename_publishershopid_shop_shopid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shopName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopPincode',
            new_name='pincode',
        ),
    ]
