# Generated by Django 4.0.2 on 2022-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_rename_shopname_shop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='firstName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='lastName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='publisherauth',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
