# Generated by Django 4.0.2 on 2022-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_alter_publisher_address_alter_publisher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
