# Generated by Django 4.0.2 on 2022-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='publisherauth',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
