# Generated by Django 4.0.2 on 2022-02-23 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_alter_publisher_pincode_alter_publisherauth_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherauth',
            name='registrationTimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
        ),
    ]
