# Generated by Django 4.0.3 on 2022-03-14 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0019_remove_publisher_registrationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='browser',
            field=models.CharField(default='localhost:chrome', max_length=255),
        ),
        migrations.AddField(
            model_name='publisher',
            name='ipAddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shop',
            name='browser',
            field=models.CharField(default='localhost:chrome', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='ipAddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='shop',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
