# Generated by Django 4.0.2 on 2022-02-22 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactId', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('dob', models.DateField()),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('contactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerauth')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
