# Generated by Django 4.0.2 on 2022-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='homeAddress',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
