# Generated by Django 4.0.3 on 2022-03-11 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_tag_tagname'),
        ('customer', '0003_remove_customer_contact_customer_homeaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('starValue', models.IntegerField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(max_length=600)),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
