# Generated by Django 4.0.3 on 2022-03-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_address_address_address_addressvalueerror_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ipAddress',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='registrationDate',
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='registrationDate',
        ),
    ]
