# Generated by Django 4.0.3 on 2022-03-15 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(choices=[('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Cooking Utensiles', 'Cooking Utensils'), ('Men Clothing', 'Men Clothing'), ('Women Clothing', 'Women Clothing'), ('Children Clothing', 'Children Clothing'), ('Winter Clothing', 'Winter Clothing'), ('Gaming Accessories', 'Gaming Accessories'), ('Mobile Phone Accessories', 'Mobile Phone Accessories'), ('Travel', 'Travel')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('companyName', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('size', models.CharField(default='-', max_length=8, null=True)),
                ('color', models.CharField(max_length=32)),
                ('discount', models.IntegerField(default=0)),
                ('edition', models.CharField(default='-', max_length=32, null=True)),
                ('feedBackValue', models.FloatField(default=0.0)),
                ('totalFeedbacks', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tagId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tag')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_product', to='users.localuser')),
            ],
        ),
    ]
