# Generated by Django 4.0.2 on 2022-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.BigAutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(choices=[('ec', 'Electronics'), ('sp', 'Sports'), ('c', 'Cooking Utensils')], max_length=64)),
            ],
        ),
    ]
