# Generated by Django 4.0.2 on 2022-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_tag_tagid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=64, unique=True)),
                ('companyBaseLocation', models.CharField(max_length=64)),
                ('companyAddress', models.CharField(max_length=128, null=True)),
                ('companyZipcode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Cooking Utensiles', 'Cooking Utensils')], max_length=64),
        ),
    ]
