# Generated by Django 4.0.2 on 2022-02-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_company_companyaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('size', models.CharField(default='-', max_length=8, null=True)),
                ('color', models.CharField(max_length=32)),
                ('edition', models.CharField(max_length=32)),
                ('discounts', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.company')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tag')),
            ],
        ),
    ]
