# Generated by Django 4.0.2 on 2022-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_tagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edition',
            field=models.CharField(default='-', max_length=32),
        ),
    ]
