# Generated by Django 4.0.2 on 2022-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Cooking Utensiles', 'Cooking Utensils'), ('Men Clothing', 'Men Clothing'), ('Women Clothing', 'Women Clothing'), ('Children Clothing', 'Children Clothing'), ('Winter Clothing', 'Winter Clothing'), ('Gaming Accessories', 'Gaming Accessories'), ('Mobile Phone Accessories', 'Mobile Phone Accessories')], max_length=64),
        ),
    ]
