# Generated by Django 4.0.2 on 2022-02-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_shop_shoppincode'),
        ('product', '0009_alter_product_edition_alter_tag_tagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounts',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='publisherId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
