# Generated by Django 4.0.3 on 2022-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feedBackValue',
            field=models.FloatField(default=0.0),
        ),
    ]
