# Generated by Django 4.0.3 on 2022-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_feedbackvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalFeedbacks',
            field=models.IntegerField(default=0),
        ),
    ]
