# Generated by Django 4.0.3 on 2022-03-14 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_totalfeedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
